global:
  scrape_interval: 15s         # 모든 target의 메트릭을 15초마다 수집
  evaluation_interval: 15s     # rule (알람 등)을 15초마다 평가

scrape_configs:
  - job_name: 'prometheus'     # Prometheus 자기 자신을 모니터링하는 job
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'            # 스프링부트 애플리케이션을 모니터링하는 job
    metrics_path: '/actuator/prometheus'   # 메트릭이 노출되는 경로
    scrape_interval: 5s                    # 이 job에 한해서 5초마다 수집
    static_configs:
      - targets: ['host.docker.internal:8080']
        # Prometheus가 도커 컨테이너에서 실행 중이고,
        # Spring Boot는 호스트(OS)에서 실행 중일 때 사용하는 주소
        # 도커 내부에서 호스트의 8080 포트 접근 시 필요 (Mac/Windows 기준)
        # 만약 Spring Boot도 도커로 실행 중이라면 service 이름:포트 로 지정해야 함