spring:
  config:
    import:
    - optional:file:.env[.properties]
    - classpath:application-rabbitmq.yml
  profiles:
    active:

  env_file:
   - .env
  flyway:
    mixed: true
    baseline-on-migrate: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/coupon-con?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20  # 크면 오히려 처리량이 떨어짐

  batch:
    job:
      enabled: false          # 애플리케이션 시작 시 Job 자동 실행 막기 Api 실행을 위해
    jdbc:
      initialize-schema: always  # 배치 메타테이블이 없으면 자동 생성


  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD}

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 3          # 최소 consumer thread 수
        max-concurrency: 5     # 최대 consumer thread 수
        prefetch: 3             # consumer 당 한번에 가져올 메시지 수
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms  # 재실행 시간
          multiplier: 2.0 # 재실행 간격
          max-interval: 10000ms  # 최대 간격시간
        default-requeue-rejected: false  # 재시도 실패 시 DLQ 있으면 보내고 없으면 폐기 (무한루프방지)



mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.example.coupon_con.infrastructure.adapter.out.persistence.mapper: DEBUG
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    jdbc: DEBUG


management:
  metrics:
    web:
      server: {}

  endpoints:
    web:
      exposure:
        include: "*"        # 모든 엔드포인트 노출
        exclude: []         # 제외할 엔드포인트 (빈 배열로 명시)
