spring:
  profiles:
    active:

  flyway:
    mixed: true
    baseline-on-migrate: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/coupon-con?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100  # 원하는 최대 커넥션 수로 변경

  batch:
    job:
      enabled: false          # 애플리케이션 시작 시 Job 자동 실행 막기 Api 실행을 위해
    jdbc:
      initialize-schema: always  # 배치 메타테이블이 없으면 자동 생성


  redis:
    host: localhost
    port: 6379
    password: 1234

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    jdbc: DEBUG


management:
  metrics:
    web:
      server: {}

  endpoints:
    web:
      exposure:
        include: "*"        # 모든 엔드포인트 노출
        exclude: []         # 제외할 엔드포인트 (빈 배열로 명시)
